### PR TITLE
Fixes #1751: Fix memory leak and lots of redrawing in Chrome

### LINKED ISSUE #1751: Memory leak in core.js
Specifically around this function call: https://github.com/uikit/uikit/blob/develop/src/js/core/core.js#L643-L674

It looks like it never returns from line 650 during an animation and recursively calls itself forever, causing a leak with the `dir` variable. Even if you were to move `dir` into the scope of that recursive call, you'd end up causing regular GC events.

I'm happy to put together a PR to fix it, but I need some context on what the `memory` variable is used for in other places of the code.

### PR DESCRIPTION
**Pull request by withinboredom**
This PR reduces the memory leak by not changing the reference of the closure `memory` and removes the closure `dir`. It creates a new object to fire the event, so it is impossible for a function consuming the event to hold onto the closure, which was also causing a memory leak.

In the wild, this allows smooth animations while scrolling and dramatically increases animation performance.

### CODE REVIEW

**Comment by aheinze** [comment]
Thanks!

File: src/js/core/core.js [hunk 1]
```diff
@@ -643,24 +643,30 @@
...
+                        
+                        // Set the direction of the scroll and store the new position
+                        if (wpxo != memory.x) memory.dir.x = wpxo > memory.x ? 1:-1 else memory.dir.x = 0;
+                        if (wpyo != memory.y) memory.dir.y = wpyo > memory.y ? 1:-1 else memory.dir.y = 0;
+                        memory.x = wpxo;
+                        memory.y = wpyo;
+                        
+                        // Trigger the scroll event, this could probably be sent using memory.clone() but this is
+                        // more explicit and easier to see exactly what is being sent in the event.
+                        UI.$doc.trigger('scrolling.uk.document', {
```
Comment (curtiskeisler) [inline src/js/core/core.js]: I didn't dig too deeply into this, but, the previous version was passing an array with a single memory type element and the new version is just passing the memory type element in to the trigger event. Not sure if the consumers will handle this change???

Comment (withinboredom) [inline src/js/core/core.js]: Good catch @curtiskeisler ... It's a super simple change, @aheinze I can fix it in another PR if you'd like.

Comment (aheinze) [inline src/js/core/core.js]: @withinboredom sure !

Comment (withinboredom) [inline src/js/core/core.js]: opened at https://github.com/uikit/uikit/pull/1756
